"""Declarative base and metadata naming convention.

The naming convention here is what makes Alembic autogenerate emit
constraint names in the format DATABASE_SPEC §5 uses everywhere
(``ix_users__phone``, ``ux_users__telegram_id``, ``fk_attempts__user_id``,
``ck_users__status_enum``). Without it, Alembic invents names like
``users_phone_idx`` and any future autogenerated migration drifts away
from the schema the database actually has.
"""

from __future__ import annotations

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase, declared_attr

# Format: <prefix>_<table>__<columns>
# The ``uq`` slot uses an ``ux_`` prefix on purpose — that is the convention
# used throughout DATABASE_SPEC §5. Composite columns are joined by `_`.
#
# ``ck`` is deliberately absent. SQLAlchemy applies a CHECK convention that
# contains ``%(constraint_name)s`` to *explicit* names too, which would turn
# ``name="ck_users__status_enum"`` into ``ck_users__ck_users__status_enum``.
# DATABASE_SPEC §5 hand-picks every CHECK name (and several use abbreviated
# table prefixes like ``ck_receipts__*`` on ``payment_receipts``), so the
# explicit-name-verbatim path is what we want. Every CheckConstraint in
# ``app/models/`` is given a full ``name=``.
NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(table_name)s__%(column_0_N_name)s",
    "uq": "ux_%(table_name)s__%(column_0_N_name)s",
    "fk": "fk_%(table_name)s__%(column_0_N_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Project-wide declarative base.

    All ORM models inherit from this. Sharing a ``MetaData`` lets Alembic
    discover every table in one autogenerate pass.

    ``eager_defaults=True`` makes SQLAlchemy issue a follow-up SELECT
    after every INSERT to load server-generated values (``created_at``,
    auto-incremented ids, etc.) into the freshly-created ORM object.
    Without this, the first access to one of those columns triggers a
    *lazy* load — which can't run on an ``AsyncSession`` outside a
    greenlet context and raises ``MissingGreenlet``. The post-INSERT
    SELECT is one extra round-trip per write, negligible at our scale
    and far cheaper than the bug class it prevents.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    @declared_attr.directive
    def __mapper_args__(cls) -> dict[str, object]:
        # ``@declared_attr.directive`` is SQLAlchemy's recommended way to
        # propagate a ``__mapper_args__`` from a non-mapped base to every
        # mapped subclass. Plain class-attribute assignment confuses
        # mypy (DeclarativeBase declares it as an instance variable).
        return {"eager_defaults": True}
